### PR TITLE
Automatically configure WebObjectActivator

### PR DESCRIPTION
**Pull request by burningice2866**
.Net Framework introduced a new WebObjectActivator property on HttpRuntime by which asp.net is able to instantiate Webforms pages, controls, handlers and modules using IoC and Dependency Injection.

This implements feature request #660

### CODE REVIEW

**Comment by burningice2866** [comment]
Why can't this pull request be merged?

**Comment by napernik** [comment]
Usually it takes a lot of operations to update our clients to a newer version of .NET.
We'll merge the PR, when we'll move to .NET 4.8, which we will likely have in 6.10 (coming in around 2-3 month) or 6.11 if not.

Version 6.9 is on its way.

**Comment by burningice2866** [comment]
Thanks for the update and roadmap.

**Comment by burningice2866** [comment]
Too bad this didn't make it into 6.10, lets hope for 6.11.

**Pull request merged**
