### PR TITLE
Feature media tags

### PR DESCRIPTION
**Pull request by dabitbol**
I added a couple of enhancements to the media library

1) The ability to add tags to a media item. This will allow us to surface media through search
2) A long awaited ability to view the URL of a media item.

### CODE REVIEW

**Comment by burningice2866** [comment]
@dabitbol Just a quick observation of the code in general

 - Properties can be written nicer using *Expression Bodied Properties* and 
 - changes to jspm.config.js and package.json should be excluded since they are not relevant to the feature.

**Comment by dabitbol** [comment]
@burningice2866 Thanks, 

1) Don't know how to exclude the file 
2) I guess, but I followed the style for the properties

Thanks for the comments

**Comment by burningice2866** [comment]
@dabitbol You can revert the changes to ` jspm.config.js` and `package.json` back to the state they had in 87830764dca29913403e983461f5c00921065e90. That way the final sum of the commits in this PR is that there are no change to those files.

**Comment by dabitbol** [comment]
Done, the files have been reverted. Thanks for the tip.

**Pull request merged**
