### PR TITLE
Change hardcoded usage of Microsoft.CSharp.CSharpProvider to instantiate it using CodeDomProvider.CreateProvider

### PR DESCRIPTION
**Pull request by burningice2866**
Change hardcoded usage of Microsoft.CSharp.CSharpProvider to instantiate it using CodeDomProvider.CreateProvider

This gives the flexibility to configure dynamic compilation via app/web.config, ie. using Roslyn for newer C# features.

Implements feature #735

### CODE REVIEW

**Comment by aeont** [comment]
@napernik it will be included in next release? Now in order to upgrade, we have to comment reference to Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider

**Comment by burningice2866** [comment]
> @napernik it will be included in next release? Now in order to upgrade, we have to comment reference to Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider

The change gives the flexibility for C1 to use the provider defined in web.config when compiling code, so it's optional to use Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider or keep using the Orchestra provider currently used by asp.net.

Basically this how it always should have been from the beginning, then it wouldn't have been an issue.

**Comment by burningice2866** [comment]
@aeont 
 - before: `var csCompiler = new CSharpCodeProvider()`
 - now: var csCompiler = (CSharpCodeProvider)CodeDomProvider.CreateProvider("c#");

**Comment by burningice2866** [comment]
Can we soon get this merged so its possible to test it "in the field" on builds based of the dev-branch?

**Pull request merged**
