### PR TITLE
Making some layout and small functional changes

### PR DESCRIPTION
**Pull request by peterpde**
I think I have implemented your recommended changes.  Tightened up the dialog layouts a little, but didn't do anything profoundly interesting with them.  They are just clean and consistent with the rest of the c1 UI.  Thanks. #615

### CODE REVIEW

**Comment by mawtex** [comment]
Sweet!

If possible, it would be awesome you got the code editors Search and Replace dialog to look just as good as the dialog you made for the visual editor.

Otherwise this looks super nice and I can pull it to dev :) Formally and need you to sign off on a [Contribution License Agreement](https://en.wikipedia.org/wiki/Contributor_License_Agreement) - can I kindly ask you to mail me at marcus.wendt@orckestra.com so we can do this?

Be aware I added a missing string, see https://github.com/Orckestra/C1-CMS-Foundation/commit/4ecfc2f9c048b8d6e8f4d1fd520f5c46e8bd2cf0

**Comment by peterpde** [comment]
Marcus,

Thank you for be willing to integrate these changes.  Please send me your contribution license agreement when you get a chance and I would be happy to sign it.

Thanks,
Peter

**Comment by mawtex** [comment]
@peterpde I still don't have your e-mail address, so please find a link to the CLA below. You can use Adobe Acrobat Reader's "Fill & Sign" feature to fill in on page two. Please mail the resulting PDF to marcus.wendt@orckestra.com  :) Thanks! @

[C1 CMS Contribution License Agreement.pdf](https://github.com/Orckestra/C1-CMS-Foundation/files/2332431/C1.CMS.Contribution.License.Agreement.pdf)

**Comment by peterpde** [comment]
Sorry about that.  Just sent the agreement via email to your marcus.wendt@orckestra.com account.

**Pull request merged**
