### PR TITLE
Making it possible to set Quality-property on ResizingOptions

### LINKED ISSUE #482: Bug: Missing setter on Quality-property when instantiating the ResizingOptions class
When outputting a ImageSrc in Razor using the Media html helper, one option is to pass a ResizingOptions instance. Unfortunately the Quality-property has no setter so one has to fallback to using an anonymous object to define each querystring parameter manually which is less safe due to missing type safety.

https://github.com/Orckestra/C1-CMS-Foundation/blob/dev/Composite/Core/WebClient/Media/ResizingOptions.cs

### PR DESCRIPTION
**Pull request by burningice2866**
Making it possible to set Quality-property on ResizingOptions

Fixes #482

### CODE REVIEW

**Comment by mawtex** [comment]
Some 40 lines changed, only change is to add a setter to a property, if I read the code right?

Before setting "quality" ensured that only values between 1 and 100, now this only happens if the value is set via a string parse. It would make sense to move the "1-100 rule" to the setter, if it is to be changable from multiple places.

**Comment by burningice2866** [comment]
Simply following your own example of tidying up files being edited like https://github.com/Orckestra/C1-CMS-Foundation/commit/4afc17e949dadfe49efd6d46c5ed6e7eb32cdad1

**Comment by burningice2866** [comment]
You're right regarding value validation, will move to the property setter and change the parse method to set the property.

**Comment by burningice2866** [comment]
There we go, commits splitted into two, including the value boundary check.

**Pull request merged**
