### PR TITLE
Created a IMailer service which acts a abstraction for sending emails

### PR DESCRIPTION
**Pull request by burningice2866**
This pull requests abstracts the sending of emails from within the CMS to be handled by a IMailer interface. The [default implementation](https://github.com/Orckestra/CMS-Foundation/pull/300/files#diff-c8e91e555656dbc26569b67af75b7e5dR6) sends emails using the [SmtpClient](https://msdn.microsoft.com/en-us/library/system.net.mail.smtpclient(v=vs.110).aspx), and there is therefor no change out-of-the-box.

The reasoning for this interface is to be able to have more control over the sending of emails from 3rd party modules like the Newsletter. Ie. have multiple smtp endpoints/server which is not supported by the default .Net mail configuration, or send emails using dedicated API's offered by [AWS](http://docs.aws.amazon.com/ses/latest/APIReference/API_SendEmail.html), [SendGrid](https://sendgrid.com/docs/API_Reference/Web_API/mail.html) and [Mandrill](https://mandrillapp.com/api/docs/messages.JSON.html#method=send).

The built-in Mail.SendMail function has been updated to use the service, which consists of two steps

 - Obtain a reference to IMailer, this can be done using DI or accessing [ServiceLocator.ApplicationServices](https://github.com/Orckestra/CMS-Foundation/blob/dev/Composite/Core/Application/ServiceLocator.cs#L37) directly
 - Call IMailer.Send with a [MailMessage](https://msdn.microsoft.com/en-us/library/system.net.mail.mailmessage(v=vs.110).aspx) object

```
var mailer = ServiceLocator.ApplicationServices.GetService<IMailer>();
var message = new MailMessage();

mailer.Send(message);
```

### CODE REVIEW

**Comment by burningice2866** [comment]
@mawtex @napernik any update?

**Comment by burningice2866** [comment]
@mawtex before the final merge, you might also fix this method, otherwise we have a async method which is actually blocking

```
public async Task SendAsync(MailMessage message)
{
  using (var client = new SmtpClient())
  {
    await client.SendMailAsync(message);
   }
}
```

to

```
public Task SendAsync(MailMessage message)
{
  using (var client = new SmtpClient())
  {
    client.SendMailAsync(message);
   }
}
```

**Comment by napernik** [comment]
That is not an equivalent change - with it **client.Dispose()** will be called before the Task returned from **client.SendMailAsync()** is executed

**Comment by burningice2866** [comment]
@napernik you're right... i was clearly smarter then than i am now :)

**Pull request merged**
